/**
 *  팝업 문구
 */
const DIALOG_ALERT_DESCRIPTION_DEFAULT = '잠시 후 다시 이용바랍니다.';
const DIALOG_ALERT_DESCRIPTION_DEFAULT2 = '잠시 후 다시 이용바랍니다.';

export { DIALOG_ALERT_DESCRIPTION_DEFAULT, DIALOG_ALERT_DESCRIPTION_DEFAULT2 };
